server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.2.3.4:3306/weixin_cqmyg?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: ***
    password: ***
logging:
  level:
    cn.yuyangyang.weixin.dao: trace
  pattern:
    console: '%p%m%n'

